"""HKEX CCASS 参与者英文名 → 中文名映射

以参与者 ID (Bxxxxx / Cxxxxx) 为主键,英文全名作 fallback。
未收录的名字会保留英文。
"""

# ID 优先查表(最可靠,名字改写也不影响)
BY_ID = {
    # C 系 — 托管银行 / Custodian banks
    'C00002': '交通银行信托',
    'C00003': '东亚银行',
    'C00010': '花旗银行',
    'C00015': '星展银行(香港)',
    'C00018': '恒生银行',
    'C00019': '汇丰银行',
    'C00028': '南洋商业银行',
    'C00033': '中国银行(香港)',
    'C00036': '建设银行(亚洲)',
    'C00037': '上海商业银行',
    'C00039': '渣打银行(香港)',
    'C00041': '华侨银行(香港)',
    'C00042': '招商永隆银行',
    'C00048': '集友银行',
    'C00058': '中信银行国际',
    'C00088': '招商银行',
    'C00093': '法国巴黎银行',

    # B 系 — 券商 / Brokers
    'B01086': '光大证券投资服务',
    'B01089': '汇丰经纪(香港)',
    'B01115': '申万宏源证券(香港)',
    'B01118': '东亚证券',
    'B01119': '中天证券',
    'B01130': '中银国际证券',
    'B01143': '海通国际证券',
    'B01148': '招商证券(香港)',
    'B01169': '大众金融证券',
    'B01181': '复星国际证券',
    'B01183': '创兴证券',
    'B01184': '华富证券',
    'B01224': '美林远东',
    'B01227': '海誉证券',
    'B01228': '中信证券经纪(香港)',
    'B01240': '顺智远证券',
    'B01256': '国金证券(香港)',
    'B01264': 'MIB证券(香港)',
    'B01265': '华侨证券(香港)',
    'B01272': '第一证券(香港)',
    'B01284': '恒生证券',
    'B01289': '南华证券',
    'B01298': '结好证券',
    'B01338': '英皇证券',
    'B01345': '辉立证券(香港)',
    'B01351': '永丰证券',
    'B01353': '大华继显(香港)',
    'B01356': '德胜证券',
    'B01407': '永旺证券',
    'B01413': '京华山一国际',
    'B01423': '保诚证券',
    'B01438': '金利丰证券',
    'B01447': 'Beta国际证券',
    'B01451': '高盛(亚洲)证券',
    'B01459': 'iFAST证券(香港)',
    'B01497': '永丰金证券(亚洲)',
    'B01508': '西南证券(香港)',
    'B01540': '一百证券',
    'B01556': '六福证券(香港)',
    'B01565': '国泰君安证券(香港)',
    'B01584': '集一证券',
    'B01590': '盈透证券(香港)',
    'B01610': 'KGI凯基证券(亚洲)',
    'B01623': '大丰银泰证券',
    'B01649': '信达国际证券',
    'B01654': '中国国际金融(中金)',
    'B01659': '喜联证券',
    'B01668': '耀才证券(国际)',
    'B01673': '富明证券',
    'B01695': '大新证券',
    'B01710': '新礼证券',
    'B01727': '工银亚洲证券',
    'B01745': '国创证券金融控股',
    'B01762': '星展唯高达(香港)',
    'B01769': '一诺证券',
    'B01813': '建银国际证券',
    'B01814': '骏溢证券',
    'B01826': '广发证券(香港)经纪',
    'B01829': '华泰金融控股(香港)',
    'B01842': '交银国际证券',
    'B01852': '天辰国际证券',
    'B01875': '国都证券(香港)',
    'B01885': '禾富证券',
    'B01890': '国信证券(香港)',
    'B01901': '招银国际证券',
    'B01904': 'Valuable Capital',
    'B01905': '国投证券(香港)',
    'B01906': '英皇国际证券',
    'B01923': 'Berkshire Capitals',
    'B01925': '博美证券',
    'B01929': '中国银河国际证券',
    'B01938': '兴业证券(香港)',
    'B01939': '东吴证券国际',
    'B01940': 'SoFi证券(香港)',
    'B01955': '富途证券国际(香港)',
    'B01959': '中泰国际证券',
    'B01967': '云锋证券',
    'B02002': '新城环球证券',
    'B02021': '新禾证券',
    'B02032': '冠玥证券',
    'B02047': '艾德证券期货',
    'B02075': '创升证券',
    'B02093': 'UpMax证券',
    'B02102': 'Zinvest Global',
    'B02120': 'Livermore Holdings',
    'B02132': 'Boom证券(香港)',
    'B02142': '老虎证券(香港)',
    'B02158': 'DT证券期货',
    'B02159': 'uSMART盈立证券',
    'B02175': '微牛证券',
    'B02195': '长桥证券(香港)',
    'B02214': '胜利证券国际(香港)',
}

# 英文名关键字映射(fallback)
BY_KEYWORD = [
    ('HKSCC', '香港中央结算'),
    ('BNP PARIBAS', '法国巴黎银行'),
    ('HONGKONG AND SHANGHAI BANKING', '汇丰银行'),
    ('HSBC BROKING', '汇丰经纪'),
    ('HSBC', '汇丰'),
    ('STANDARD CHARTERED', '渣打银行'),
    ('CITIBANK', '花旗银行'),
    ('CITIGROUP', '花旗环球金融'),
    ('JPMORGAN', '摩根大通'),
    ('J.P. MORGAN', '摩根大通'),
    ('DEUTSCHE BANK', '德意志银行'),
    ('GOLDMAN SACHS', '高盛'),
    ('MORGAN STANLEY', '摩根士丹利'),
    ('MERRILL LYNCH', '美林'),
    ('UBS', '瑞银'),
    ('CREDIT SUISSE', '瑞信'),
    ('NOMURA', '野村'),
    ('DAIWA', '大和证券'),
    ('MACQUARIE', '麦格理'),
    ('BARCLAYS', '巴克莱'),
    ('SOCIETE GENERALE', '法国兴业银行'),
    ('MIZUHO', '瑞穗'),
    ('CLSA', '里昂证券'),
    ('BANK OF CHINA (HONG KONG)', '中国银行(香港)'),
    ('BANK OF CHINA', '中国银行'),
    ('CONSTRUCTION BANK', '建设银行'),
    ('INDUSTRIAL AND COMMERCIAL BANK', '工商银行'),
    ('ICBC', '工商银行(亚洲)'),
    ('AGRICULTURAL BANK', '农业银行'),
    ('COMMUNICATIONS', '交通银行'),
    ('CITIC', '中信'),
    ('HAITONG', '海通'),
    ('CICC', '中金'),
    ('CHINA INTERNATIONAL CAPITAL', '中金公司'),
    ('HUATAI', '华泰证券'),
    ('GF SECURITIES', '广发证券'),
    ('GUOSEN', '国信证券'),
    ('GUOTAI JUNAN', '国泰君安'),
    ('SHENWAN HONGYUAN', '申万宏源'),
    ('CHINA GALAXY', '中国银河'),
    ('CHINA MERCHANTS', '招商'),
    ('ZHONGTAI', '中泰国际'),
    ('SOOCHOW', '东吴国际'),
    ('CHINA INDUSTRIAL', '兴业证券'),
    ('CITIC CLSA', '中信里昂'),
    ('BOCI', '中银国际'),
    ('BOCOM', '交银国际'),
    ('ABCI', '农银国际'),
    ('CCB INTERNATIONAL', '建银国际'),
    ('CMB INTERNATIONAL', '招银国际'),
    ('CMB', '招商'),
    ('EVERBRIGHT', '光大'),
    ('HANG SENG', '恒生'),
    ('DBS', '星展'),
    ('OCBC', '华侨'),
    ('UOB', '大华'),
    ('CATHAY', '国泰'),
    ('TAISHIN', '台新'),
    ('MAYBANK', '马来亚银行'),
    ('SINOPAC', '永丰金'),
    ('FUBON', '富邦'),
    ('KGI', '凯基'),
    ('YUANTA', '元大'),
    ('PHILLIP', '辉立'),
    ('FUTU', '富途'),
    ('TIGER BROKERS', '老虎证券'),
    ('LONG BRIDGE', '长桥'),
    ('WEBULL', '微牛'),
    ('USMART', 'uSMART盈立'),
    ('INTERACTIVE BROKERS', '盈透证券'),
    ('BRIGHT SMART', '耀才证券'),
    ('EMPEROR', '英皇'),
    ('KINGSTON', '金利丰'),
    ('GET NICE', '结好证券'),
    ('HOORAY', '海誉'),
    ('BERKSHIRE', '博克夏'),
    ('FULBRIGHT', '富明'),
    ('CORE PACIFIC', '京华山一'),
    ('SUN HUNG KAI', '新鸿基'),
    ('DBS VICKERS', '星展唯高达'),
    ('CHONG HING', '创兴'),
    ('DAH SING', '大新'),
    ('EAST ASIA', '东亚'),
    ('WING LUNG', '永隆'),
    ('NANYANG COMMERCIAL', '南洋商业'),
    ('SHANGHAI COMMERCIAL', '上海商业'),
    ('CITIC BANK', '中信银行'),
    ('CHIYU BANK', '集友银行'),
    ('EDDID', '艾德证券'),
    ('INNOVAX', '创升'),
    ('SDIC', '国投'),
    ('YUNFENG', '云锋'),
    ('SOFI', 'SoFi'),
    ('BOOM SECURITIES', 'Boom证券'),
    ('CHEER UNION', '喜联证券'),
    ('ONE CHINA', '一诺'),
    ('WINBULL', '胜利证券'),
    ('UPBEST', '一百'),
    ('IMPERIUM', '英皇国际'),
    ('DELTA ASIA', '德胜'),
    ('FB SECURITIES', '第一证券'),
    ('LUK FOOK', '六福'),
    ('CELESTIAL', '中天'),
    ('TAI FUNG', '大丰'),
    ('SOUTHWEST', '西南'),
    ('SOUTH CHINA SECURITIES', '南华'),
    ('ZINVEST', 'Zinvest'),
    ('WELL LINK', '骏溢'),
    ('CINDA INTERNATIONAL', '信达国际'),
    ('LIVERMORE', 'Livermore'),
    ('WIN WONG', '永旺'),
    ('WING FUNG', '永丰'),
    ('TSUN CHI YUEN', '顺智远'),
    ('HAFOO', '禾富'),
    ('PRUDENTIAL BROKERAGE', '保诚'),
    ('FOSUN', '复星'),
    ('NEW HARVEST', '新禾'),
    ('FORTHRIGHT', '冠玥'),
    ('MIB SECURITIES', 'MIB证券'),
    ('SINOLINK', '国金'),
    ('UPMAX', 'UpMax'),
    ('GUODU', '国都'),
    ('GUOCHUANG', '国创'),
    ('BMI SECURITIES', '博美证券'),
    ('ARTA GLOBAL', '天辰国际'),
    ('CHIEF SECURITIES', '集一证券'),
    ('VALUABLE CAPITAL', 'Valuable Capital'),
    ('QUAM', '华富'),
    ('DT SECURITIES', 'DT证券'),
    ('SINO-RICH', '新礼'),
    ('IFAST', 'iFAST'),
    ('SEAZEN', '新城环球'),
]


def to_chinese(pid, english_name):
    """把 HKEX 参与者名字翻译成中文。未知返回原英文。"""
    if pid and pid in BY_ID:
        return BY_ID[pid]
    if not english_name:
        return english_name
    upper = english_name.upper()
    for kw, cn in BY_KEYWORD:
        if kw in upper:
            return cn
    return english_name


def display_name(pid, english_name):
    """返回展示名:中文 + 原文(若有差异),或仅原文。"""
    cn = to_chinese(pid, english_name)
    if cn and cn != english_name:
        return cn
    return english_name
